version: "3.8"
services:
  app-npm:
    build:
      context: .
      dockerfile: Dockerfile.npm
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

  app-pnpm:
    build:
      context: .
      dockerfile: Dockerfile.pnpm
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

  app-bun:
    build:
      context: .
      dockerfile: Dockerfile.bun
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
